# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbafffdee6fb6d160c12bbbf8dbd4e39197afc78b237973eb58fbf8fbe283fb4f4410c8064790fd909d45ac2ec721ea1f17aa2e0d5be1d83be047c9279286d27

test:
  secret_key_base: 8257cf9fc6fc16a4a21b515f19a9efd5cb8cc13a3c292cbb9e2b26d14efa58d6aa8873d683fdef85661491a85fe5648a055fbd33fe5906b0b35576797d82a115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
